"""
Southern Spear - import and place the original Red Gum homestead (class F).

Places the compound generated by Tools/Blender/redgum_homestead.py on
/Game/Maps/L_RedGum_01 and authors its materials. Idempotent: on rerun it
removes only the actors it owns (label prefix SS_RedGum_Homestead_), so it can
be re-run after a Blender change without duplicating the station or touching
the pack's trees, fences or the objectives.

Why it is a separate pass from the dressing (expand_redgum.py): the dressing
pass owns everything with the SS_RedGum_Dress_v1_ prefix and deletes exactly
that set on rerun. If the homestead shared that prefix, a dressing rerun would
delete the station and then not put it back. Separate prefixes, separate
lifecycles, and neither pass can silently eat the other's work.

COLLISION POLICY, PER STRUCTURE - this is the part that is easy to get wrong

    farmhouse, shearing shed, hut, water tank : SOLID. These are the centre
        objective's hard cover and must be in the navmesh.
    stock pens, windmill : NO COLLISION. A one-piece convex hull around the
        joined stock-pen mesh would be a solid 18 x 13 m block - an invisible
        wall in the middle of the yard with the rails nowhere near its surface.
        The windmill has the same problem in miniature. Both are also thin
        enough that the honest options are "no collision" (what the pack's wire
        fences already do, ADR-022) or per-rail colliders, and per-rail
        colliders are a later pass, not a guess made in a placement script.

THE FAITHFUL-TRACE-FLAG LESSON (R-10)

The mesh is asked for SIMPLE collision at import and the trace flag is then
written unconditionally and read back. dress_dryriver.py shipped a run that
reported ok while the write silently did nothing, because the enum member it
asked for did not exist. So: assert the read-back, and count the simple
collision elements, which is what distinguishes "the mesh has no collision"
from "str(KAggregateGeom) is an opaque pointer and tells you nothing".

REPORT: Build/redgum_homestead_report.json (git-ignored).
"""

import csv
import json
import math
import os
import traceback

import unreal

PROJECT_DIR = unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir())
MAP = "/Game/Maps/L_RedGum_01"
ART_DIR = os.path.join(PROJECT_DIR, "Content", "Art", "Environment", "RedGum")
CSV_PATH = os.path.join(ART_DIR, "SS_RedGum_Homestead_Layout.csv")
DEST = "/Game/Art/Environment/RedGum"
MAT_DEST = DEST + "/Materials"
REPORT = os.path.join(PROJECT_DIR, "Build", "redgum_homestead_report.json")

PREFIX = "SS_RedGum_Homestead_"
FOLDER = unreal.Name("RedGum/Homestead")

# Slot name authored in Blender (SS_RedGum_<Slot>) -> authored UE material.
# Base colours are dry-country: dust-pale green boards, red-oxide iron,
# silvered timber, dark glass, galvanised metal. No texture is sampled from
# anywhere; these are constants, so the station carries no third-party licence
# dependency of any kind (L-0011 class F).
MATERIALS = {
    "Wall":   ((0.352, 0.372, 0.302), 0.78, 0.0),   # r, g, b, roughness, metallic
    "Roof":   ((0.196, 0.070, 0.042), 0.62, 0.25),
    "Timber": ((0.185, 0.150, 0.110), 0.85, 0.0),
    "Glass":  ((0.014, 0.020, 0.024), 0.10, 0.0),
    "Metal":  ((0.330, 0.348, 0.360), 0.38, 0.85),
}

# Textured look (Session 041, producer: "very poor quality, just a block"): where the Singapore Canal pack
# (L-0016 Fab licence) is installed, its weathered materials replace the constants above; the meshes carry
# box-projected UVs from redgum_homestead.py. Without the pack the constants are used, as before.
PACK_MATERIALS = {
    "Wall": "/Game/Singapore_Canal/Materials/MI_WoodPainted_01",
    "Roof": "/Game/Art/Environment/Fab/CorrugatedIron/MI_SS_CorrugatedIron",
    "Metal": "/Game/Art/Environment/Fab/CorrugatedIron/MI_SS_CorrugatedIron",
    "Timber": "/Game/Singapore_Canal/Materials/MI_WoodOldRaw_01",
}


def pack_material(key):
    path = PACK_MATERIALS.get(key)
    if not path or not unreal.EditorAssetLibrary.does_asset_exist(path):
        return None
    m = unreal.load_asset(path)
    return m if isinstance(m, unreal.MaterialInterface) else None


# Solid where the structure is meant to stop a player, open where a hull would
# be a lie. See the module docstring.
NO_COLLISION = {"StockPens", "Windmill"}

# The farmhouse pad is the largest footprint (12 x 8 m plus a 2.6 m verandah).
# Used only to report the yard's clear extent, not to place anything.
actor_sub = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
report = {"ok": False, "map": MAP, "steps": [], "materials": {},
          "structures": [], "errors": [], "warnings": []}


def step(name, ok, detail=""):
    report["steps"].append({"step": name, "ok": bool(ok), "detail": str(detail)})
    unreal.log("[RedGumHomestead] {} {} {}".format("OK  " if ok else "FAIL", name, detail))
    return bool(ok)


def warn(msg):
    report["warnings"].append(str(msg))
    unreal.log("[RedGumHomestead] WARN {}".format(msg))


# ---------------------------------------------------------------------------
# Materials
# ---------------------------------------------------------------------------

def build_materials():
    """Author the five station materials as constants on fresh material assets.

    Created with MaterialFactoryNew and rebuilt every run, because a half-built
    material (colour wired, roughness not) is the classic silent-no-op and a
    map full of wrong-coloured buildings is worse than no buildings.
    """
    mel = unreal.MaterialEditingLibrary
    made = {}
    for slot, (rgb, rough, metal) in MATERIALS.items():
        name = "M_SS_RedGum_" + slot
        path = MAT_DEST + "/" + name
        if unreal.EditorAssetLibrary.does_asset_exist(path):
            unreal.EditorAssetLibrary.delete_asset(path)
        factory = unreal.MaterialFactoryNew()
        mat = unreal.AssetToolsHelpers.get_asset_tools().create_asset(
            name, MAT_DEST, unreal.Material, factory)
        if mat is None:
            report["errors"].append("could not create " + path)
            continue

        def constant(cls, y, value, prop="r"):
            expr = mel.create_material_expression(mat, cls, -400, y)
            expr.set_editor_property(prop, value)
            return expr

        base = mel.create_material_expression(
            mat, unreal.MaterialExpressionConstant3Vector, -700, 120)
        base.set_editor_property("constant", unreal.LinearColor(rgb[0], rgb[1], rgb[2], 1.0))
        mel.connect_material_property(base, "", unreal.MaterialProperty.MP_BASE_COLOR)
        mel.connect_material_property(
            constant(unreal.MaterialExpressionConstant, -60, rough), "",
            unreal.MaterialProperty.MP_ROUGHNESS)
        mel.connect_material_property(
            constant(unreal.MaterialExpressionConstant, -260, metal), "",
            unreal.MaterialProperty.MP_METALLIC)
        mel.recompile_material(mat)
        unreal.EditorAssetLibrary.save_loaded_asset(mat)
        made[slot] = mat
    # Return the assets, not the step verdict: step() returns a bool, and
    # returning that here made main()'s len(materials) raise on a bool.
    step("author_materials", len(made) == len(MATERIALS),
         "{} of {}".format(len(made), len(MATERIALS)))
    return made


# ---------------------------------------------------------------------------
# Import
# ---------------------------------------------------------------------------

def simple_collision_element_count(mesh):
    """Count stored simple-collision elements. str(KAggregateGeom) cannot."""
    body = mesh.get_editor_property("body_setup")
    geom = body.get_editor_property("agg_geom")
    total = 0
    for prop in ("box_elems", "sphere_elems", "convex_elems",
                 "tapered_capsule_elems", "level_set_elems"):
        try:
            total += len(geom.get_editor_property(prop))
        except Exception:  # noqa: BLE001 - a missing array is simply zero
            pass
    return total


def import_structure(label, materials):
    """Import one FBX, force simple collision, override its material slots."""
    fbx = os.path.join(ART_DIR, "SS_RedGum_{}.fbx".format(label))
    if not os.path.isfile(fbx):
        report["errors"].append("missing FBX " + fbx)
        return None

    task = unreal.AssetImportTask()
    task.set_editor_property("filename", fbx)
    task.set_editor_property("destination_path", DEST)
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", True)
    task.set_editor_property("save", True)

    opts = unreal.FbxImportUI()
    for prop, value in (("import_mesh", True),
                        ("import_as_skeletal", False),
                        ("import_animations", False),
                        ("import_materials", True),
                        ("import_textures", False)):
        try:
            opts.set_editor_property(prop, value)
        except Exception as exc:  # noqa: BLE001
            warn("FbxImportUI.{}: {}".format(prop, exc))
    try:
        smi = opts.get_editor_property("static_mesh_import_data")
        smi.set_editor_property("combine_meshes", True)
        smi.set_editor_property("auto_generate_collision", True)
        smi.set_editor_property("generate_lightmap_u_vs", False)
    except Exception as exc:  # noqa: BLE001
        warn("static_mesh_import_data: {}".format(exc))
    task.set_editor_property("options", opts)

    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])
    imported = list(task.get_editor_property("imported_object_paths") or [])
    if not imported:
        report["errors"].append("import produced nothing for " + label)
        return None

    path = "{}/SS_RedGum_{}".format(DEST, label)
    mesh = unreal.load_asset(path)
    if not isinstance(mesh, unreal.StaticMesh):
        report["errors"].append("no StaticMesh at " + path)
        return None

    # CTF_USE_DEFAULT, written and read back. See R-10 in the docstring.
    flag, applied = unreal.CollisionTraceFlag.CTF_USE_DEFAULT, ""
    try:
        body = mesh.get_editor_property("body_setup")
        body.set_editor_property("collision_trace_flag", flag)
        applied = str(body.get_editor_property("collision_trace_flag"))
    except Exception as exc:  # noqa: BLE001
        report["errors"].append("{}: collision_trace_flag: {}".format(label, exc))
    if "CTF_USE_DEFAULT" not in applied:
        report["errors"].append("{}: trace flag is {!r}, not CTF_USE_DEFAULT".format(label, applied))

    # Slot override by name. The FBX carries slot names from the Blender
    # materials, so this is a lookup rather than an ordering assumption.
    #
    # StaticMesh.Materials is a protected property on 5.8 and raises on read;
    # StaticMaterials is the array that actually holds the slot names, so the
    # slot list is read from there and written back through set_material.
    slots = list(mesh.get_editor_property("static_materials"))
    assigned, unresolved = [], []
    for index, sm in enumerate(slots):
        slot_name = str(sm.get_editor_property("material_slot_name"))
        key = slot_name.replace("SS_RedGum_", "").strip("_")
        target = pack_material(key) or materials.get(key)
        if target is None:
            unresolved.append(slot_name)
            continue
        mesh.set_material(index, target)
        assigned.append(slot_name)
    if unresolved:
        warn("{}: unresolved slots {}".format(label, unresolved))

    # Drop the empty instance constants the FBX importer created; every slot now
    # points at an authored material and the leftovers are unreferenced clutter.
    for obj_path in imported:
        if obj_path == path:
            continue
        asset = unreal.load_asset(obj_path)
        if isinstance(asset, unreal.MaterialInterface):
            unreal.EditorAssetLibrary.delete_asset(obj_path)

    unreal.EditorAssetLibrary.save_loaded_asset(mesh)
    report["structures"].append({
        "name": label,
        "path": path,
        "trace_flag": applied,
        "simple_collision_elements": simple_collision_element_count(mesh),
        "slots_assigned": assigned,
        "slots_unresolved": unresolved,
    })
    return mesh


# ---------------------------------------------------------------------------
# Placement
# ---------------------------------------------------------------------------

def ground_z(world, x, y):
    hit = unreal.SystemLibrary.line_trace_single(
        world, unreal.Vector(x, y, 50000.0), unreal.Vector(x, y, -50000.0),
        unreal.TraceTypeQuery.TRACE_TYPE_QUERY1, True, [],
        unreal.DrawDebugTrace.NONE, True)
    if hit is None:
        return None
    hr = hit[1] if isinstance(hit, (list, tuple)) and len(hit) > 1 and hit[0] else hit
    try:
        return hr.to_dict()["impact_point"].z
    except Exception:  # noqa: BLE001
        return None


def ground_z_median(world, x, y, half_x, half_y, cols=5, rows=4, margin=0.0):
    """Median ground height over a footprint, in cm.

    A single centre trace is not a building's ground height. On Red Gum it
    returned the top of a gum tree standing inside the footprint and lifted the
    shearing shed 1.66 m into the air, and a centre trace through a placed
    building returns its own roof. Sampling a grid across the footprint and
    taking the median fixes the first; the seating check deliberately samples
    OUTSIDE the footprint so it stays an independent measurement of the second.
    """
    samples = []
    for r in range(rows):
        for c in range(cols):
            px = x + (half_x + margin) * ((c / float(cols - 1)) * 2.0 - 1.0)
            py = y + (half_y + margin) * ((r / float(rows - 1)) * 2.0 - 1.0)
            gz = ground_z(world, px, py)
            if gz is not None:
                samples.append(gz)
    if not samples:
        return None
    samples.sort()
    mid = len(samples) // 2
    if len(samples) % 2:
        return samples[mid]
    return (samples[mid - 1] + samples[mid]) / 2.0


def remove_owned_actors():
    removed = 0
    for actor in actor_sub.get_all_level_actors():
        if actor.get_actor_label().startswith(PREFIX):
            actor_sub.destroy_actor(actor)
            removed += 1
    report["removed_previous_pass"] = removed
    return removed


def objective_b(world):
    """The centre objective, found by label rather than hard-coded coordinates.

    Hard-coding would silently move the station if layout_objectives.py ever
    re-lays the objectives, which is exactly the kind of coupling that makes a
    map look broken a month later.
    """
    objectives = unreal.GameplayStatics.get_all_actors_of_class(world, unreal.SSObjectiveActor)
    for actor in objectives:
        if "ObjB" in actor.get_actor_label():
            return actor
    for actor in objectives:
        if "Homestead" in actor.get_actor_label():
            return actor
    return objectives[1] if len(objectives) > 1 else None


def place(meshes, world, anchor, rows):
    """Place each structure at its CSV offset from the anchor, snapped to ground.

    Blender-space metres to UE centimetres, with Y negated and yaw flipped to
    match: the FBX is exported axis_forward='-Z', axis_up='Y', which maps
    Blender +Y to UE -Y. The same handedness rule is applied by
    dress_dryriver.py, and both passes agree on it deliberately.
    """
    placed = 0
    for row in rows:
        name, structure = row["name"], row["structure"]
        mesh = meshes.get(name)
        if mesh is None:
            continue
        x_m, y_m = float(row["x_m"]), float(row["y_m"])
        yaw = -float(row["yaw_deg"])
        scale = float(row.get("scale") or 1.0)

        loc = unreal.Vector(anchor.x + x_m * 100.0, anchor.y - y_m * 100.0, 0.0)

        # The CSV carries the measured footprint, so the ground height is the
        # median under the whole building rather than one point that might be a
        # tree, a log or the building itself.
        half_x = float(row.get("half_x_m") or 2.0) * 100.0 * scale
        half_y = float(row.get("half_y_m") or 2.0) * 100.0 * scale
        base_z_m = row.get("base_z_m")
        if base_z_m is not None and abs(float(base_z_m)) > 0.05:
            report["errors"].append(
                "{}: authored base is at z={} m, not 0; it would sit {} m off the ground"
                .format(name, base_z_m, base_z_m))
        z = ground_z_median(world, loc.x, loc.y, half_x, half_y)
        if z is None:
            warn("no ground hit under {} ({:.0f}, {:.0f})".format(name, loc.x, loc.y))
            continue
        loc.z = z

        # spawn_actor_from_object refuses a mesh imported in this same session
        # ("SpawnActorFromObject. No actor was spawned." with no further
        # detail), so spawn the actor class and hand it the mesh instead - the
        # same route dress_dryriver.py uses successfully.
        actor = actor_sub.spawn_actor_from_class(
            unreal.StaticMeshActor, loc, unreal.Rotator(roll=0.0, pitch=0.0, yaw=yaw))
        if not actor:
            report["errors"].append("spawn returned None for " + name)
            continue
        actor.static_mesh_component.set_static_mesh(mesh)
        actor.set_actor_label(PREFIX + name)
        try:
            actor.set_folder_path(FOLDER)
        except Exception:  # noqa: BLE001 - foldering is cosmetic
            pass
        actor.set_actor_scale3d(unreal.Vector(scale, scale, scale))

        collide = name not in NO_COLLISION
        actor.set_actor_enable_collision(collide)
        actor.static_mesh_component.set_collision_profile_name(
            "BlockAll" if collide else "NoCollision")

        # No vertical offset. Every structure in redgum_homestead.py is authored
        # with its base exactly at local z = 0 (slab bottoms, post feet and leg
        # feet all start at 0), so the traced ground height IS the actor height.
        #
        # Two earlier versions tried to compensate using the mesh's own bounds
        # and both buried the station: asking a just-imported asset for its
        # bounds in the same session returns a degenerate box, so the computed
        # offset was a full height of earth. The verify step below measures the
        # actor's real world bounds against the ground instead, which is the
        # quantity that matters - if a future Blender edit breaks the
        # base-at-origin convention, that step fails loudly.
        actor.set_actor_location(loc, False, False)

        for entry in report["structures"]:
            if entry["name"] == name:
                origin_b, extent_b = actor.get_actor_bounds(False)
                entry["location_cm"] = [round(actor.get_actor_location().x),
                                        round(actor.get_actor_location().y),
                                        round(actor.get_actor_location().z)]
                entry["world_bounds_cm"] = {
                    "min": [round(origin_b.x - extent_b.x), round(origin_b.y - extent_b.y),
                            round(origin_b.z - extent_b.z)],
                    "max": [round(origin_b.x + extent_b.x), round(origin_b.y + extent_b.y),
                            round(origin_b.z + extent_b.z)],
                }
                entry["collision"] = collide
                entry["structure"] = structure
        placed += 1
    return placed


def verify_solid(world, meshes, rows):
    """Prove the solid structures block a trace AND sit on the ground.

    Two separate failure modes, measured separately. A trace hit alone is not
    enough: a structure buried up to its roofline is still a trace hit, and
    that is exactly what a wrong vertical offset produces. The seating check
    is the one that catches it.
    """
    checked = 0
    unseated = []
    for actor in actor_sub.get_all_level_actors():
        label = actor.get_actor_label()
        if not label.startswith(PREFIX):
            continue
        name = label[len(PREFIX):]
        if name in NO_COLLISION:
            continue
        loc = actor.get_actor_location()
        origin, extent = actor.get_actor_bounds(False)
        # Probe a small cross inside the footprint; the middle of a stock pen
        # is empty ground, so a single centre trace would under-report.
        probes = 0
        hits = 0
        for dx, dy in ((0.0, 0.0), (extent.x * 0.5, 0.0), (-extent.x * 0.5, 0.0),
                       (0.0, extent.y * 0.5), (0.0, -extent.y * 0.5)):
            res = unreal.SystemLibrary.line_trace_single(
                world, unreal.Vector(origin.x + dx, origin.y + dy, loc.z + 800.0),
                unreal.Vector(origin.x + dx, origin.y + dy, loc.z - 800.0),
                unreal.TraceTypeQuery.TRACE_TYPE_QUERY1, True, [],
                unreal.DrawDebugTrace.NONE, True)
            hit = res[0] if isinstance(res, (list, tuple)) and res else res is not None
            probes += 1
            hits += 1 if hit else 0
        checked += 1

        # Seating: the actor's world bounds bottom against the ground just
        # OUTSIDE its footprint, measured on a ring so it is independent of the
        # median the placement used. Tracing down through the centre of a
        # placed building returns its own roof, which reported every structure
        # as buried by its own height; sampling outside is immune to that.
        # +-0.35 m is slack for land that is not flat under a 16 m shed, but far
        # tighter than a float.
        seated_m = None
        ring = []
        ring_pts = []
        for i in range(8):
            ang = math.tau * i / 8.0
            ring_pts.append((math.cos(ang), math.sin(ang)))
        for dx, dy in ring_pts:
            gz = ground_z(world, origin.x + dx * (extent.x + 120.0),
                          origin.y + dy * (extent.y + 120.0))
            if gz is not None:
                ring.append(gz)
        if ring:
            ring.sort()
            gz = ring[len(ring) // 2] if len(ring) % 2 else (
                ring[len(ring) // 2 - 1] + ring[len(ring) // 2]) / 2.0
            seated_m = round((origin.z - extent.z - gz) / 100.0, 2)
            if abs(seated_m) > 0.35:
                unseated.append("{} {}".format(name, seated_m))

        for entry in report["structures"]:
            if entry["name"] == name:
                entry["trace_probes"] = "{} of {}".format(hits, probes)
                entry["solid"] = hits > 0
                entry["base_minus_ground_m"] = seated_m
    report["unseated"] = unseated
    return checked


# ---------------------------------------------------------------------------

def main():
    if not os.path.isfile(CSV_PATH):
        report["errors"].append("missing layout CSV " + CSV_PATH)
        return
    with open(CSV_PATH, "r", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    step("read_layout_csv", bool(rows), "{} rows".format(len(rows)))

    world = unreal.EditorLoadingAndSavingUtils.load_map(MAP)
    if not step("load_map", world is not None, MAP):
        return

    materials = build_materials()
    if len(materials) != len(MATERIALS):
        return

    meshes = {}
    for row in rows:
        mesh = import_structure(row["name"], materials)
        if mesh is not None:
            meshes[row["name"]] = mesh
    step("import_structures", len(meshes) == len(rows),
        "{} of {} imported".format(len(meshes), len(rows)))
    report["materials"] = {k: v.get_path_name() for k, v in materials.items()}

    anchor_actor = objective_b(world)
    if not step("find_objective_b", anchor_actor is not None,
                 anchor_actor.get_actor_label() if anchor_actor else "none"):
        return
    anchor = anchor_actor.get_actor_location()
    report["anchor_cm"] = [round(anchor.x), round(anchor.y), round(anchor.z)]
    report["anchor_label"] = anchor_actor.get_actor_label()

    remove_owned_actors()
    placed = place(meshes, world, anchor, rows)
    step("place_structures", placed == len(rows),
         "{} of {} placed".format(placed, len(rows)))

    checked = verify_solid(world, meshes, rows)
    solid = [e for e in report["structures"] if e.get("collision")]
    missing = [e["name"] for e in solid if not e.get("solid")]
    step("verify_collision", not missing,
         "{} solid structures traced, missing {}".format(len(solid), missing or "none"))
    step("verify_ground_seating", not report["unseated"],
         "base-to-ground deviation over 0.35 m: {}".format(report["unseated"] or "none"))
    report["verified_solid_count"] = checked

    saved = bool(unreal.get_editor_subsystem(unreal.LevelEditorSubsystem).save_current_level())
    step("save_map", saved, MAP)
    report["ok"] = all(s["ok"] for s in report["steps"])


try:
    main()
except Exception:  # noqa: BLE001
    report["errors"].append(traceback.format_exc())
    unreal.log_error("[RedGumHomestead] raised:\n" + traceback.format_exc())
finally:
    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2, default=str)
    unreal.log("[RedGumHomestead] complete ok={} report={}".format(report.get("ok"), REPORT))
