# Southern Spear - Quantum body prototype, setup (Session 058).
#
# Criterion 2 of the prototype is ADFRC camouflage on the Quantum shirt and trousers. The camo
# sheet is generated by Tools/Textures/make_adfrc_camo.py, whose palette is measured from the
# ADFRC Crye_G3_Shirt_DPC source rather than invented, and the vendor UV layout is left alone:
# a periodic pattern through untouched UVs cannot seam, which a bake over someone else's sheet
# eventually always does.
#
# The Quantum modules are DUPLICATED into /SSExp_ObjectiveAssault/Characters/QuantumProto rather
# than referenced in place, for two reasons: the camo material assignment would otherwise edit
# the vendor pack's own meshes, and the prototype needs our own copy to survive a pack update.
# A duplicate keeps its original skeleton, so SK_Military_Character_Skeleton stays on the mesh
# and nothing is reparented to the mannequin (ADR-036/037/038).
#
# Idempotent: re-running re-imports the texture, rebuilds the material graph in place, re-applies
# the slot overrides and re-saves the map. It never deletes a blueprint or a mesh to recreate it
# (delete_asset silently no-ops on .uasset files headlessly, Session 051).
#
# Writes Build/quantum_proto_setup.json.
import json
import os
import sys
import traceback

import unreal

# does_asset_exist() misses Game Feature assets in a commandlet; see Tools/Unreal/ss_assets.py.
sys.path.insert(0, os.path.join(unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir()), "Tools", "Unreal"))
from ss_assets import asset_exists  # noqa: E402

PROJECT_DIR = unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir())
REPORT = os.path.join(PROJECT_DIR, "Build", "quantum_proto_setup.json")

QC = "/Game/QuantumCharacter/Mesh/Modules/"
DEST = "/SSExp_ObjectiveAssault/Characters/QuantumProto"
MAP = "/Game/Maps/L_SS_QuantumProto"
CAMO_SRC = os.path.join(PROJECT_DIR, "Art", "Characters", "ADF", "T_ADFRC_DPC_camo.png")
CAMO_TEX = "/Game/Art/Characters/ADF/T_ADFRC_DPC_camo"
FABRIC_NORMAL = DEST.rsplit("/", 1)[0] + "/Textures/T_SS_Gear_N"
FABRIC_ORM = DEST.rsplit("/", 1)[0] + "/Textures/T_SS_Gear_ORM"
CAMO_MAT = DEST + "/M_SS_ADFRC_Camo"

# Camouflage UV tiling per garment. The Quantum UVs are the vendor's, so the density is not
# known until it is on screen; these are the values the first render was judged on.
CAMLESS = ("SKM_Head", "SKM_Arms")
GARMENTS = {
    "SKM_Shirt_RolledUp_Blue": ("MI_SS_ADFRC_Camo_Shirt", 3.0),
    "SKM_Jeans": ("MI_SS_ADFRC_Camo_Jeans", 4.0),
}
# R-91, measured 2026-09-30: mesh-asset material slots are READ-ONLY from Python in 5.8 -
# set_editor_property on the materials array returns without error and without effect
# (probe_quantum_material.py). The shipping camo therefore does NOT edit these meshes at all:
# setup_soldiers.py assigns the material instances below as FriendlyMaterialOverrides, riding
# on the character-part components (ADR-004). This script builds the materials and instances
# those overrides point at, and records the vendor slots they replace.

report = {"ok": False, "steps": [], "errors": []}
tools = unreal.AssetToolsHelpers.get_asset_tools()
mel = unreal.MaterialEditingLibrary


def step(name, ok, detail=""):
    report["steps"].append({"step": name, "ok": bool(ok), "detail": str(detail)})
    unreal.log("SS_QSETUP {} {} {}".format(name, "ok" if ok else "FAIL", detail))
    return bool(ok)


def import_camo_texture():
    if not os.path.isfile(CAMO_SRC):
        return None
    task = unreal.AssetImportTask()
    task.set_editor_property("filename", CAMO_SRC)
    task.set_editor_property("destination_path", "/Game/Art/Characters/ADF")
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", True)
    task.set_editor_property("save", True)
    tools.import_asset_tasks([task])
    texture = unreal.load_asset(CAMO_TEX)
    step("camo_texture", texture is not None, CAMO_TEX)
    if texture is not None:
        try:
            texture.set_editor_property("srgb", True)
            texture.set_editor_property("virtual_texture_streaming", False)
            texture.modify()
        except Exception as exc:
            report["errors"].append("camo texture props: " + str(exc))
    return texture


def build_camo_material(texture, fabric_normal, fabric_orm):
    """Opaque camo cloth with a generated twill normal and packed surface channels.

    The vendor UV layout stays untouched. CamouflageTiling controls the DPC pattern scale,
    while FabricDetailTiling independently controls the generated weave normal and surface variation.
    """
    name = CAMO_MAT.split("/")[-1]
    folder = CAMO_MAT.rsplit("/", 1)[0]
    if asset_exists(CAMO_MAT):
        material = unreal.load_asset(CAMO_MAT)
        # Idempotent graph: clear the nodes earlier runs laid down before laying the
        # same nodes down again, or every rerun compounds the graph (12 expressions
        # after two runs, measured).
        mel.delete_all_material_expressions(material)
    else:
        material = tools.create_asset(name, folder, unreal.Material, unreal.MaterialFactoryNew())
    if material is None:
        step("camo_material", False, "create returned None")
        return None

    E = unreal
    coord = mel.create_material_expression(material, E.MaterialExpressionTextureCoordinate, -1600, 0)
    tiling = mel.create_material_expression(material, E.MaterialExpressionScalarParameter, -1400, 200)
    tiling.set_editor_property("parameter_name", "CamouflageTiling")
    tiling.set_editor_property("default_value", 3.0)
    scale = mel.create_material_expression(material, E.MaterialExpressionMultiply, -1200, 0)
    mel.connect_material_expressions(coord, "", scale, "A")
    mel.connect_material_expressions(tiling, "", scale, "B")
    sample = mel.create_material_expression(material, E.MaterialExpressionTextureSampleParameter2D, -1000, -200)
    sample.set_editor_property("parameter_name", "CamoMap")
    sample.set_editor_property("texture", texture)
    mel.connect_material_expressions(scale, "", sample, "UVs")
    mel.connect_material_property(sample, "RGB", E.MaterialProperty.MP_BASE_COLOR)

    # Keep the fine weave detail independent of garment-specific camo scale: multiplying the
    # 300-cycle normal map by the 3x/4x camo tiling would alias it on screen.
    fabric_tiling = mel.create_material_expression(material, E.MaterialExpressionScalarParameter, -1400, 500)
    fabric_tiling.set_editor_property("parameter_name", "FabricDetailTiling")
    fabric_tiling.set_editor_property("default_value", 1.0)
    fabric_scale = mel.create_material_expression(material, E.MaterialExpressionMultiply, -1200, 400)
    mel.connect_material_expressions(coord, "", fabric_scale, "A")
    mel.connect_material_expressions(fabric_tiling, "", fabric_scale, "B")

    normal_sample = mel.create_material_expression(material, E.MaterialExpressionTextureSampleParameter2D, -1000, 40)
    normal_sample.set_editor_property("parameter_name", "FabricNormalMap")
    normal_sample.set_editor_property("texture", fabric_normal)
    normal_sample.set_editor_property("sampler_type", E.MaterialSamplerType.SAMPLERTYPE_NORMAL)
    mel.connect_material_expressions(fabric_scale, "", normal_sample, "UVs")
    mel.connect_material_property(normal_sample, "RGB", E.MaterialProperty.MP_NORMAL)

    orm_sample = mel.create_material_expression(material, E.MaterialExpressionTextureSampleParameter2D, -1000, 300)
    orm_sample.set_editor_property("parameter_name", "FabricORM")
    orm_sample.set_editor_property("texture", fabric_orm)
    mel.connect_material_expressions(fabric_scale, "", orm_sample, "UVs")
    mel.connect_material_property(orm_sample, "R", E.MaterialProperty.MP_AMBIENT_OCCLUSION)
    mel.connect_material_property(orm_sample, "G", E.MaterialProperty.MP_ROUGHNESS)
    mel.connect_material_property(orm_sample, "B", E.MaterialProperty.MP_METALLIC)

    material_settings_ok = True
    for editor_property, value in (("shading_model", E.MaterialShadingModel.MSM_DEFAULT_LIT),
                                   ("two_sided", False),
                                   ("use_material_attributes", False),
                                   ("used_with_skeletal_mesh", True)):
        try:
            material.set_editor_property(editor_property, value)
        except Exception as exc:
            material_settings_ok = False
            report["errors"].append("material {}: {}".format(editor_property, exc))
    compiled = True
    try:
        mel.recompile_material(material)
    except Exception as exc:
        compiled = False
        report["errors"].append("material compile: " + str(exc))
    saved = False
    try:
        saved = unreal.EditorAssetLibrary.save_loaded_asset(material, only_if_is_dirty=False)
    except Exception as exc:
        report["errors"].append("material save: " + str(exc))
    ok = material_settings_ok and compiled and saved
    step("camo_material", ok, "{} (compiled={}, saved={})".format(CAMO_MAT, compiled, saved))
    return material if ok else None


def build_instance(material, instance_name, tiling):
    path = DEST + "/" + instance_name
    if asset_exists(path):
        instance = unreal.load_asset(path)
    else:
        factory = unreal.MaterialInstanceConstantFactoryNew()
        instance = tools.create_asset(instance_name, DEST, unreal.MaterialInstanceConstant, factory)
        if instance is not None:
            instance.set_editor_property("parent", material)
    if instance is None:
        return None
    mel.set_material_instance_scalar_parameter_value(instance, "CamouflageTiling", tiling)
    mel.set_material_instance_scalar_parameter_value(instance, "FabricDetailTiling", 1.0)
    mel.update_material_instance(instance)
    return instance


def duplicate_module(name):
    source = QC + name
    target = DEST + "/" + name
    if not asset_exists(source):
        step("source:" + name, False, source)
        return None
    if asset_exists(target):
        return unreal.load_asset(target)
    duplicated = unreal.EditorAssetLibrary.duplicate_asset(source, target)
    step("duplicate:" + name, duplicated is not None, target)
    return duplicated


def apply_camo(mesh, instance, name):
    """Record what the vendor slots carry; do not write them (read-only from Python, R-91).
    The shipping camo rides on component overrides (setup_soldiers.py), which point at the
    instances this script builds and saves."""
    slots = mesh.get_editor_property("materials")
    unreal.EditorAssetLibrary.save_loaded_asset(mesh, only_if_is_dirty=False)
    vendor = [s.get_editor_property("material_interface").get_path_name()
              if s.get_editor_property("material_interface") else None for s in slots]
    return len(slots), vendor


def build_map():
    if not hasattr(unreal, "SSQuantumProtoStage"):
        step("stage_class", False, "unreal.SSQuantumProtoStage is not exposed to Python")
        return None
    les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    if not asset_exists(MAP):
        created = les.new_level(MAP)
        step("new_level", bool(created), MAP)
    else:
        unreal.EditorLoadingAndSavingUtils.load_map(MAP)

    actors = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    for actor in actors.get_all_level_actors():
        if isinstance(actor, unreal.SSQuantumProtoStage):
            actors.destroy_actor(actor)
    stage = actors.spawn_actor_from_class(
        unreal.SSQuantumProtoStage, unreal.Vector(0.0, 0.0, 0.0), unreal.Rotator(roll=0, pitch=0, yaw=0))
    step("spawn_stage", stage is not None, MAP)
    saved = unreal.EditorLoadingAndSavingUtils.save_current_level()
    step("save_map", bool(saved), MAP)
    return stage


def main():
    texture = import_camo_texture()
    fabric_normal = unreal.load_asset(FABRIC_NORMAL)
    fabric_orm = unreal.load_asset(FABRIC_ORM)
    step("fabric_surface_maps", fabric_normal is not None and fabric_orm is not None,
         "normal={} ORM={}".format(FABRIC_NORMAL if fabric_normal else None,
                                   FABRIC_ORM if fabric_orm else None))
    if fabric_normal is not None:
        try:
            fabric_normal.modify()
            fabric_normal.set_editor_property("srgb", False)
            fabric_normal.set_editor_property("compression_settings", unreal.TextureCompressionSettings.TC_NORMALMAP)
            saved = unreal.EditorAssetLibrary.save_loaded_asset(fabric_normal, only_if_is_dirty=False)
            if not saved:
                raise RuntimeError("save_loaded_asset failed")
        except Exception as exc:
            report["errors"].append("fabric normal settings: " + str(exc))
            fabric_normal = None
    if fabric_orm is not None:
        try:
            fabric_orm.modify()
            fabric_orm.set_editor_property("srgb", False)
            fabric_orm.set_editor_property("compression_settings", unreal.TextureCompressionSettings.TC_MASKS)
            saved = unreal.EditorAssetLibrary.save_loaded_asset(fabric_orm, only_if_is_dirty=False)
            if not saved:
                raise RuntimeError("save_loaded_asset failed")
        except Exception as exc:
            report["errors"].append("fabric ORM settings: " + str(exc))
            fabric_orm = None
    material = (build_camo_material(texture, fabric_normal, fabric_orm)
                if texture is not None and fabric_normal is not None and fabric_orm is not None else None)

    instances = {}
    for name, (instance_name, tiling) in GARMENTS.items():
        instance = build_instance(material, instance_name, tiling) if material else None
        instances[name] = (instance, tiling)
        step("instance:" + instance_name, instance is not None, "tiling {}".format(tiling))

    meshes = {}
    for name in list(GARMENTS) + list(CAMLESS):
        meshes[name] = duplicate_module(name)

    # The master and the instances MUST be saved before they are assigned to a mesh: the
    # first run assigned unsaved transient assets and saved only the meshes, so the commandlet
    # exit deleted the material out from under the slots and the shirt rendered plain white.
    # (Session 058's report said "camo exists"; the screen said otherwise.)
    if material is not None:
        saved = unreal.EditorAssetLibrary.save_asset(CAMO_MAT, only_if_is_dirty=False)
        step("save:camo_material", bool(saved), CAMO_MAT)
    for name, (instance, _tiling) in instances.items():
        if instance is not None:
            path = DEST + "/" + GARMENTS[name][0]
            saved = unreal.EditorAssetLibrary.save_asset(path, only_if_is_dirty=False)
            step("save:" + GARMENTS[name][0], bool(saved), path)

    for name, (instance, _tiling) in instances.items():
        mesh = meshes.get(name)
        if mesh is None or instance is None:
            continue
        count, vendor = apply_camo(mesh, instance, name)
        step("camo_slots:" + name, count > 0, "{} slots (vendor: {}) -> override {}".format(
            count, vendor, instance.get_path_name()))

    for name in CAMLESS:
        mesh = meshes.get(name)
        if mesh is None:
            continue
        try:
            slots = mesh.get_editor_property("materials")
            detail = ["{}={}".format(
                s.get_editor_property("material_slot_name"),
                (s.get_editor_property("material_interface").get_path_name()
                 if s.get_editor_property("material_interface") else "None")) for s in slots]
            step("as_authored:" + name, True, "; ".join(detail)[:300])
        except Exception as exc:
            report["errors"].append("slots " + name + ": " + str(exc))

    for name in meshes:
        if meshes[name] is not None:
            unreal.EditorAssetLibrary.save_asset(DEST + "/" + name, only_if_is_dirty=False)

    build_map()

    report["ok"] = all(s["ok"] for s in report["steps"]) and not report["errors"]
    with open(REPORT, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=1)
    unreal.log("SS_QSETUP_DONE ok={} steps={} errors={}".format(
        report["ok"], len(report["steps"]), len(report["errors"])))


try:
    main()
except Exception:
    report["errors"].append(traceback.format_exc())
    with open(REPORT, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=1)
    unreal.log("SS_QSETUP_DONE ok=False (exception)")
