# Southern Spear - Quantum body prototype, setup (Session 058).
#
# Criterion 2 of the prototype is ADFRC camouflage on the Quantum shirt and trousers. The camo
# sheet is generated by Tools/Textures/make_adfrc_camo.py, whose palette is measured from the
# ADFRC Crye_G3_Shirt_DPC source rather than invented, and the vendor UV layout is left alone:
# a periodic pattern through untouched UVs cannot seam, which a bake over someone else's sheet
# eventually always does.
#
# The Quantum modules are DUPLICATED into /SSExp_ObjectiveAssault/Characters/QuantumProto rather
# than referenced in place, for two reasons: the camo material assignment would otherwise edit
# the vendor pack's own meshes, and the prototype needs our own copy to survive a pack update.
# A duplicate keeps its original skeleton, so SK_Military_Character_Skeleton stays on the mesh
# and nothing is reparented to the mannequin (ADR-036/037/038).
#
# Idempotent: re-running re-imports the texture, rebuilds the material graph in place, re-applies
# the slot overrides and re-saves the map. It never deletes a blueprint or a mesh to recreate it
# (delete_asset silently no-ops on .uasset files headlessly, Session 051).
#
# Writes Build/quantum_proto_setup.json.
import json
import os
import sys
import traceback

import unreal

# does_asset_exist() misses Game Feature assets in a commandlet; see Tools/Unreal/ss_assets.py.
sys.path.insert(0, os.path.join(unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir()), "Tools", "Unreal"))
from ss_assets import asset_exists  # noqa: E402

PROJECT_DIR = unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir())
REPORT = os.path.join(PROJECT_DIR, "Build", "quantum_proto_setup.json")

QC = "/Game/QuantumCharacter/Mesh/Modules/"
DEST = "/SSExp_ObjectiveAssault/Characters/QuantumProto"
MAP = "/Game/Maps/L_SS_QuantumProto"
CAMO_SRC = os.path.join(PROJECT_DIR, "Art", "Characters", "ADF", "T_ADFRC_DPC_camo.png")
CAMO_TEX = "/Game/Art/Characters/ADF/T_ADFRC_DPC_camo"
CAMO_MAT = DEST + "/M_SS_ADFRC_Camo"

# Camouflage UV tiling per garment. The Quantum UVs are the vendor's, so the density is not
# known until it is on screen; these are the values the first render was judged on.
CAMLESS = ("SKM_Head", "SKM_Arms")
GARMENTS = {
    "SKM_Shirt_RolledUp_Blue": ("MI_SS_ADFRC_Camo_Shirt", 3.0),
    "SKM_Jeans": ("MI_SS_ADFRC_Camo_Jeans", 4.0),
}

report = {"ok": False, "steps": [], "errors": []}
tools = unreal.AssetToolsHelpers.get_asset_tools()
mel = unreal.MaterialEditingLibrary


def step(name, ok, detail=""):
    report["steps"].append({"step": name, "ok": bool(ok), "detail": str(detail)})
    unreal.log("SS_QSETUP {} {} {}".format(name, "ok" if ok else "FAIL", detail))
    return bool(ok)


def import_camo_texture():
    if not os.path.isfile(CAMO_SRC):
        return None
    task = unreal.AssetImportTask()
    task.set_editor_property("filename", CAMO_SRC)
    task.set_editor_property("destination_path", "/Game/Art/Characters/ADF")
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", True)
    task.set_editor_property("save", True)
    tools.import_asset_tasks([task])
    texture = unreal.load_asset(CAMO_TEX)
    step("camo_texture", texture is not None, CAMO_TEX)
    if texture is not None:
        try:
            texture.set_editor_property("srgb", True)
            texture.set_editor_property("virtual_texture_streaming", False)
            texture.modify()
        except Exception as exc:
            report["errors"].append("camo texture props: " + str(exc))
    return texture


def build_camo_material(texture):
    """Opaque fabric: camo through untouched vendor UVs, tiled by a scalar so one master serves
    the shirt and the trousers at different densities. Roughness is a constant rather than a
    sampled map - the vendor's fabric normal and roughness are dropped in the prototype, which
    is a fidelity cost worth recording rather than hiding."""
    name = CAMO_MAT.split("/")[-1]
    folder = CAMO_MAT.rsplit("/", 1)[0]
    if asset_exists(CAMO_MAT):
        material = unreal.load_asset(CAMO_MAT)
        # Rebuild the graph: the simplest way to be idempotent is to lay the same nodes down
        # again and reconnect them, rather than trying to find the old ones by name.
    else:
        material = tools.create_asset(name, folder, unreal.Material, unreal.MaterialFactoryNew())
    if material is None:
        step("camo_material", False, "create returned None")
        return None

    E = unreal
    coord = mel.create_material_expression(material, E.MaterialExpressionTextureCoordinate, -1600, 0)
    tiling = mel.create_material_expression(material, E.MaterialExpressionScalarParameter, -1400, 200)
    tiling.set_editor_property("parameter_name", "CamouflageTiling")
    tiling.set_editor_property("default_value", 3.0)
    scale = mel.create_material_expression(material, E.MaterialExpressionMultiply, -1200, 0)
    mel.connect_material_expressions(coord, "", scale, "A")
    mel.connect_material_expressions(tiling, "", scale, "B")
    sample = mel.create_material_expression(material, E.MaterialExpressionTextureSampleParameter2D, -1000, -200)
    sample.set_editor_property("parameter_name", "CamoMap")
    sample.set_editor_property("texture", texture)
    mel.connect_material_expressions(scale, "", sample, "UVs")
    mel.connect_material_property(sample, "RGB", E.MaterialProperty.MP_BASE_COLOR)

    rough = mel.create_material_expression(material, E.MaterialExpressionScalarParameter, -1000, 300)
    rough.set_editor_property("parameter_name", "FabricRoughness")
    rough.set_editor_property("default_value", 0.86)
    mel.connect_material_property(rough, "", E.MaterialProperty.MP_ROUGHNESS)
    metal = mel.create_material_expression(material, E.MaterialExpressionConstant, -1000, 450)
    metal.set_editor_property("r", 0.0)
    mel.connect_material_property(metal, "", E.MaterialProperty.MP_METALLIC)

    for editor_property, value in (("shading_model", E.MaterialShadingModel.MSM_DEFAULT_LIT),
                                   ("two_sided", False),
                                   ("use_material_attributes", False)):
        try:
            material.set_editor_property(editor_property, value)
        except Exception as exc:
            report["errors"].append("material {}: {}".format(editor_property, exc))
    mel.recompile_material(material)
    step("camo_material", True, CAMO_MAT)
    return material


def build_instance(material, instance_name, tiling):
    path = DEST + "/" + instance_name
    if asset_exists(path):
        instance = unreal.load_asset(path)
    else:
        factory = unreal.MaterialInstanceConstantFactoryNew()
        instance = tools.create_asset(instance_name, DEST, unreal.MaterialInstanceConstant, factory)
        if instance is not None:
            instance.set_editor_property("parent", material)
    if instance is None:
        return None
    mel.set_material_instance_scalar_parameter_value(instance, "CamouflageTiling", tiling)
    mel.set_material_instance_scalar_parameter_value(instance, "FabricRoughness", 0.86)
    mel.update_material_instance(instance)
    return instance


def duplicate_module(name):
    source = QC + name
    target = DEST + "/" + name
    if not asset_exists(source):
        step("source:" + name, False, source)
        return None
    if asset_exists(target):
        return unreal.load_asset(target)
    duplicated = unreal.EditorAssetLibrary.duplicate_asset(source, target)
    step("duplicate:" + name, duplicated is not None, target)
    return duplicated


def apply_camo(mesh, instance):
    slots = mesh.get_editor_property("materials")
    for index, slot in enumerate(slots):
        slot.set_editor_property("material_interface", instance)
    mesh.set_editor_property("materials", slots)
    return len(slots)


def build_map():
    if not hasattr(unreal, "SSQuantumProtoStage"):
        step("stage_class", False, "unreal.SSQuantumProtoStage is not exposed to Python")
        return None
    les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    if not asset_exists(MAP):
        created = les.new_level(MAP)
        step("new_level", bool(created), MAP)
    else:
        unreal.EditorLoadingAndSavingUtils.load_map(MAP)

    actors = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    for actor in actors.get_all_level_actors():
        if isinstance(actor, unreal.SSQuantumProtoStage):
            actors.destroy_actor(actor)
    stage = actors.spawn_actor_from_class(
        unreal.SSQuantumProtoStage, unreal.Vector(0.0, 0.0, 0.0), unreal.Rotator(roll=0, pitch=0, yaw=0))
    step("spawn_stage", stage is not None, MAP)
    saved = unreal.EditorLoadingAndSavingUtils.save_current_level()
    step("save_map", bool(saved), MAP)
    return stage


def main():
    texture = import_camo_texture()
    material = build_camo_material(texture) if texture else None

    instances = {}
    for name, (instance_name, tiling) in GARMENTS.items():
        instance = build_instance(material, instance_name, tiling) if material else None
        instances[name] = (instance, tiling)
        step("instance:" + instance_name, instance is not None, "tiling {}".format(tiling))

    meshes = {}
    for name in list(GARMENTS) + list(CAMLESS):
        meshes[name] = duplicate_module(name)

    # The master and the instances MUST be saved before they are assigned to a mesh: the
    # first run assigned unsaved transient assets and saved only the meshes, so the commandlet
    # exit deleted the material out from under the slots and the shirt rendered plain white.
    # (Session 058's report said "camo exists"; the screen said otherwise.)
    if material is not None:
        unreal.EditorAssetLibrary.save_asset(CAMO_MAT, only_if_is_dirty=False)
        step("save:camo_material", True, CAMO_MAT)
    for name, (instance, _tiling) in instances.items():
        if instance is not None:
            path = DEST + "/" + GARMENTS[name][0]
            unreal.EditorAssetLibrary.save_asset(path, only_if_is_dirty=False)
            step("save:" + GARMENTS[name][0], True, path)

    for name, (instance, _tiling) in instances.items():
        mesh = meshes.get(name)
        if mesh is None or instance is None:
            continue
        count = apply_camo(mesh, instance)
        mesh.modify()
        step("camo_slots:" + name, count > 0, "{} slots -> {}".format(
            count, instance.get_path_name()))

    for name in CAMLESS:
        mesh = meshes.get(name)
        if mesh is None:
            continue
        try:
            slots = mesh.get_editor_property("materials")
            detail = ["{}={}".format(
                s.get_editor_property("material_slot_name"),
                (s.get_editor_property("material_interface").get_path_name()
                 if s.get_editor_property("material_interface") else "None")) for s in slots]
            step("as_authored:" + name, True, "; ".join(detail)[:300])
        except Exception as exc:
            report["errors"].append("slots " + name + ": " + str(exc))

    for name in meshes:
        if meshes[name] is not None:
            unreal.EditorAssetLibrary.save_asset(DEST + "/" + name, only_if_is_dirty=False)

    build_map()

    report["ok"] = all(s["ok"] for s in report["steps"])
    with open(REPORT, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=1)
    unreal.log("SS_QSETUP_DONE ok={} steps={} errors={}".format(
        report["ok"], len(report["steps"]), len(report["errors"])))


try:
    main()
except Exception:
    report["errors"].append(traceback.format_exc())
    with open(REPORT, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=1)
    unreal.log("SS_QSETUP_DONE ok=False (exception)")
