// Copyright Southern Spear. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "SSQuantumProtoStage.generated.h"

class UCameraComponent;
class UDirectionalLightComponent;
class UPoseableMeshComponent;
class USkeletalMesh;
class USkeletalMeshComponent;
class USkyLightComponent;
class UStaticMeshComponent;
struct FReferenceSkeleton;

/**
 * The bone correspondence between a source skeleton and a target skeleton, plus the
 * per-bone fallback for the target bones the source does not have.
 */
struct FSSQuantumBoneMap
{
	/** Source bone index for each target bone; INDEX_NONE where the source has no match. */
	TArray<int32> SourceForTarget;

	TArray<int32> TargetParent;
	TArray<FName> TargetNames;

	/** 1 on a finger bone: a target bone under a hand that the source cannot drive. */
	TArray<uint8> DigitMask;

	/** Reference pose with the grip curl already applied, for the digits. */
	TArray<FTransform> DigitCurl;

	/**
	 * Bones whose NAME matched but whose meaning did not, so they are left on the target's own
	 * reference pose. Matching on name alone is not enough: both rigs carry an `ik_hand_l`, a
	 * helper bone, but at 281 cm apart in the two skeletons, and driving one from the other
	 * throws the hand across the body. Rejecting these is what a hand-authored retarget chain
	 * map buys, and it is why the chain map cannot simply be generated by name.
	 */
	TArray<FName> RejectedBones;
	TArray<float> RejectedOffsetDeltaCm;
	TArray<float> RejectedAngleDeltaDeg;

	/** Twist and IK helper bones left out of the map, as UE's own IK Retargeter does. */
	int32 TwistExcluded = 0;
};

/**
 * Capture stage and runtime retarget for the Quantum body prototype (Session 058).
 *
 * One pose source, two bodies. The pose source is the same Manny skeleton the current
 * soldier is built on. The two followers deliberately use different mechanisms, because
 * which mechanism works is the question the prototype answers:
 *
 *  - The G3 soldier uses leader pose, exactly as ASSCharacterPartActor sets it today, so
 *    one half of the shot is the shipping soldier rather than a reconstruction of it.
 *  - The Quantum modules are UPoseableMeshComponent followers driven by EvaluateRetarget.
 *    They have to be: UE 5.8 removed both USkeletalMeshComponentPostProcessAnimInstance
 *    and UAnimInstance::NativeEvaluateAnimation, and the IKRetargeter asset cannot be
 *    authored from Python (no IKRetargeterFactory, no AnimBlueprint graph API - see
 *    Build/probe_retargeter.json). Leader pose is the only engine-supported
 *    cross-skeleton lever that survives, and it cannot author a joint angle on a bone the
 *    leader does not have, which is the whole of the hand.
 *
 * The retarget maps bones by name and carries the source's motion *relative to the
 * source's own parent* onto the target's parent, so the Quantum skeleton keeps its own
 * bone lengths instead of being stretched onto Manny's armature. The 192 bones Manny does
 * not have (fingers, toes, face) have no source data to copy, so they keep the vendor
 * reference pose - and the finger bones are given a grip curl, because a hand welded
 * straight to a rifle is the visible tell of a body swap.
 *
 * Lives in SouthernSpearLyraBridge, not SouthernSpearCore. Core is the root of the SS
 * dependency graph and holds the shared types every other module uses; a capture harness that
 * names specific Quantum and mannequin assets does not belong there, even though it happens to
 * reach no gameplay state. Tools/validate_architecture.py only inspects module dependencies, so
 * it passed in Core and could not have caught this - which is the point of saying so in the ADR.
 */
UCLASS(NotBlueprintable)
class SSBRIDGE_API ASSQuantumProtoStage : public AActor
{
	GENERATED_BODY()

public:
	ASSQuantumProtoStage();

	virtual void BeginPlay() override;
	virtual void Tick(float DeltaSeconds) override;

	/**
	 * 0 = fingers straight, 1 = closed grip. Drives only the Quantum-only finger bones;
	 * every bone the mannequin has a match for comes from the pose source.
	 */
	UPROPERTY(EditAnywhere, Category = "SS|Quantum", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float FingerCurl = 1.0f;

	/** Degrees of curl per finger joint at FingerCurl = 1. */
	UPROPERTY(EditAnywhere, Category = "SS|Quantum", meta = (ClampMin = "0.0", ClampMax = "90.0"))
	float CurlDegreesPerJoint = 55.0f;

	/** Take the view on BeginPlay, so a -game capture run frames the stage. */
	UPROPERTY(EditAnywhere, Category = "SS|Quantum")
	bool bTakeView = true;

	/**
	 * Measure whether the ADFRC plate carrier still fits Quantum's torso (criterion 3).
	 * Static so a commandlet can call it without a world: Tools/Unreal/prove_quantum_retarget.py
	 * does exactly that, which is how this number is obtained on a machine with no display.
	 */
	UFUNCTION(BlueprintCallable, Category = "SS|Quantum")
	static void LogFitReport();

	/**
	 * Prove the retarget without a renderer, from a commandlet.
	 *
	 * A retarget that cannot be seen is not evidence, and a -game capture needs a display
	 * this machine does not currently have. So the same BuildBoneMap and EvaluateRetarget
	 * the runtime uses are run here over two reference skeletons and checked against three
	 * invariants:
	 *
	 *  A. Rest is a fixed point. With the source in its own reference pose, every mapped
	 *     target bone must land on the target's own reference transform, because a resting
	 *     skeleton has no relative motion to carry. Any drift means the map is wrong.
	 *  B. Motion propagates relatively. Rotating one source bone must rotate the matching
	 *     target bone by the same amount *about its own parent*, which is the difference
	 *     between a retarget and a world-transform copy.
	 *  C. Proportions survive. The parent-to-child offset length of the moved bone must be
	 *     unchanged by the motion. This is what would break if the code copied world
	 *     transforms and dragged Quantum's arm onto Manny's arm length.
	 *
	 * Returns a JSON report whose "ok" field is true when all three hold. The report is
	 * RETURNED rather than written to a UFUNCTION out-parameter: UE 5.8's Python wrapper
	 * surfaces a bool return as None and drops a `FString&` out-param entirely, so a
	 * (bool, FString&) signature is uncallable from a commandlet and silently returns None.
	 */
	UFUNCTION(BlueprintCallable, Category = "SS|Quantum")
	static FString ProveRetarget(const FString& PoseSourceMeshPath, const FString& TargetMeshPath,
		float Curl, float CurlDegrees);

private:
	UPoseableMeshComponent* AddQuantumPart(const FString& ObjectPath, const FVector& Offset);
	USkeletalMeshComponent* AddG3Part(const FString& ObjectPath, const FVector& Offset);
	void RetargetBody(UPoseableMeshComponent* Part);

	/** True when BoneIndex sits under a hand bone: a finger, not the wrist. */
	static bool IsDigitBone(const FReferenceSkeleton& Ref, int32 BoneIndex, bool& bOutIsHandItself);

	/** Reference-pose local transform of a digit bone, curled about its flexion axis. */
	static FTransform CurledDigitTransform(const FReferenceSkeleton& Ref, int32 BoneIndex,
		float Curl, float CurlDegrees);

	/**
	 * Name correspondence from a source skeleton to a target skeleton, rejecting the matches
	 * that do not survive a rest-pose sanity check. Shared by the runtime and ProveRetarget, so
	 * the proof tests the code that ships.
	 *
	 * A match is kept only when the two rigs agree about the joint: the bone's offset from its
	 * parent is within OffsetToleranceCm and its rest rotation within AngleToleranceDeg. Two
	 * skeletons of the same build agree closely; a shared name on a helper or prop bone does
	 * not, and driving the target from the source there moves a limb to the wrong place.
	 */
	static int32 BuildBoneMap(const FReferenceSkeleton& Source, const FReferenceSkeleton& Target,
		const TMap<FName, int32>& SourceByName, float Curl, float CurlDegrees, FSSQuantumBoneMap& Out);

	/**
	 * Map the source's local pose onto the target, in target component space.
	 * Shared by the runtime and ProveRetarget.
	 */
	static void EvaluateRetarget(const FSSQuantumBoneMap& Map, const TArray<FTransform>& SourceLocal,
		const TArray<FTransform>& TargetRefPose, TArray<FTransform>& OutComponentSpace);

	/** Component-space transforms of a skeleton sitting in its own reference pose. */
	static void ReferenceComponentSpace(const FReferenceSkeleton& Ref, TArray<FTransform>& Out);

	UPROPERTY()
	TObjectPtr<USceneComponent> StageRoot;

	UPROPERTY()
	TObjectPtr<UPoseableMeshComponent> PoseSource;

	UPROPERTY()
	TArray<TObjectPtr<USkeletalMeshComponent>> G3Parts;

	UPROPERTY()
	TArray<TObjectPtr<UPoseableMeshComponent>> QuantumParts;

	UPROPERTY()
	TObjectPtr<UStaticMeshComponent> Platform;

	/** Matte ground plane under the plinth: the unlit surround otherwise reads as a void. */
	UPROPERTY()
	TObjectPtr<UStaticMeshComponent> Floor;

	UPROPERTY()
	TObjectPtr<UCameraComponent> Camera;

	UPROPERTY()
	TObjectPtr<UDirectionalLightComponent> Sun;

	UPROPERTY()
	TObjectPtr<USkyLightComponent> Fill;

	/** Source bone index by name, for the pose source's skeleton. */
	TMap<FName, int32> SourceByName;

	/** Local-space pose captured from the pose source this tick. */
	TArray<FTransform> SourceLocal;

	TArray<FName> SourceNames;
	TArray<int32> SourceParent;

	FSSQuantumBoneMap BoneMap;
	TArray<FTransform> Scratch;
};
