#!/usr/bin/env python3
"""Download and self-host the website's font subsets.

The page used to depend on a render-blocking third-party stylesheet from
fonts.googleapis.com, which cost an extra DNS lookup and TLS handshake before
any text could paint. This pulls the latin subsets once, stores them under
Site/fonts/, and emits Site/fonts/fonts.css with local-only @font-face rules.

Re-run when the type stack changes:

    python Tools/build_site_fonts.py
"""

import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Site", "fonts")
CSS_OUT = os.path.join(OUT, "fonts.css")

FAMILIES = (
    "Barlow+Condensed:wght@600;700",
    "Inter:wght@400;600",
    "IBM+Plex+Mono:wght@400;600",
)
SUBSETS = ("latin",)
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

SLUG = {"Barlow Condensed": "barlow-condensed",
        "Inter": "inter",
        "IBM Plex Mono": "ibm-plex-mono"}


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def main():
    os.makedirs(OUT, exist_ok=True)
    url = "https://fonts.googleapis.com/css2?family={}&display=swap".format(
        "&family=".join(FAMILIES))
    css = fetch(url).decode("utf-8")

    # Google emits "/* subset */" immediately before each @font-face block.
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)

    rules, seen = [], {}
    for subset, block in blocks:
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip()
        style = re.search(r"font-style:\s*([^;]+);", block).group(1).strip()
        src = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        rng = re.search(r"unicode-range:\s*([^;]+);", block)
        unicode_range = rng.group(1).strip() if rng else None

        key = (family, weight, style)
        if key in seen:
            continue
        seen[key] = True

        # Google serves one variable file per family/subset; name it once.
        filename = "{}-{}.woff2".format(SLUG.get(family, "font"), subset)
        path = os.path.join(OUT, filename)
        if not os.path.exists(path) or src not in seen.get("_src", set()):
            data = fetch(src)
            with open(path, "wb") as fh:
                fh.write(data)
            print("  {}  {:.1f} KB".format(filename, len(data) / 1024))

        rule = ["@font-face {",
                "  font-family: '{}';".format(family),
                "  font-style: {};".format(style),
                "  font-weight: {};".format(weight),
                "  font-display: swap;",
                "  src: url('{}') format('woff2');".format(filename)]
        if unicode_range:
            rule.append("  unicode-range: {};".format(unicode_range))
        rule.append("}")
        rules.append("\n".join(rule))

    header = ("/* Self-hosted font subsets. Generated by Tools/build_site_fonts.py.\n"
              "   Barlow Condensed, Inter and IBM Plex Mono are all licensed under the\n"
              "   SIL Open Font License 1.1. Do not edit by hand. */\n\n")
    with open(CSS_OUT, "w", encoding="utf-8") as fh:
        fh.write(header + "\n\n".join(rules) + "\n")
    print("wrote", os.path.relpath(CSS_OUT, ROOT), "({} rules)".format(len(rules)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
